# Generated by Django 4.1.4 on 2022-12-25 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128)),
                ('description', models.CharField(default=None, max_length=180)),
                ('imgurl', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.URLField(blank=True, max_length=1024, null=True)),
                ('source', models.CharField(default=None, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_newsfeeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
