# Generated by Django 4.1.4 on 2022-12-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='article',
            name='timestamps',
            field=models.DateTimeField(null=True),
        ),
    ]
